FROM debian:bookworm-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    bc \
    bison \
    build-essential \
    ca-certificates \
    flex \
    libncurses-dev \
    perl \
    python3 \
    rsync \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /work/src
